### ISSUE TITLE
crash on filechange

### ISSUE THREAD

**Issue by biiiipy** [facebook/fb-flo#63]
When I change a file, there's a 1 in maybe 6 chance, that the server will crash. Error:
```
\fb-flo\node_modules\sane\node_modules\watch\main.js:122
    if (prevFile.file === null || prevFile.stat.mtime.getTime() !== curr.mtime
                                               ^
TypeError: Cannot read property 'mtime' of undefined
    at \fb-flo\node_modules\sane\node_modules\watch\main.js:122:48
    at StatWatcher.<anonymous> (\fb-flo\node_modules\sane\node_modules\watch\main.js:73:38)
    at StatWatcher.emit (events.js:98:17)
    at StatWatcher._handle.onchange (fs.js:1109:10)
```

**Comment by amasad** [comment]
This has been fixed in sane project. Reopen if it's still a problem
